using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UIElements;

namespace VirtualMaker.Bindings.Extensions
{
    public static partial class BindingsExtensions
    {
        // <Auto-generated>
    }
}